[aws]
symbol = "ï”­ "

[cmake]
symbol = "â–³ "

[cobol]
symbol = "âš™ï¸ "

[conda]
symbol = "îœ¼ "

[crystal]
symbol = "ğŸ”® "

[dart]
symbol = "î˜ "

[deno]
symbol = "ğŸ¦• "

[directory]
read_only = " ï€£"

[docker_context]
symbol = "ïŒˆ "

[dotnet]
symbol = "îœ® "

[elixir]
symbol = "î˜­ "

[elm]
symbol = "î˜¬ "

[erlang]
symbol = "î± "

[gcloud]
symbol = "ï”­ "

[git_branch]
symbol = "î‚  "

[git_commit]
tag_symbol = " ï€« "

[golang]
symbol = "ï³‘ "

[helm]
symbol = "âˆ "

[hg_branch]
symbol = "î‚  "

[java]
symbol = "îœ¸ "

[julia]
symbol = "î˜¤ "

[kotlin]
symbol = "îœ¸ "

[kubernetes]
symbol = "â˜¸ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "ï¢˜ "

[ocaml]
symbol = "ğŸ« "

[openstack]
symbol = "â˜ï¸  "

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "îœ½ "

[pulumi]
symbol = "ï†² "

[purescript]
symbol = "<=> "

[python]
symbol = "îœ¼ "

[red]
symbol = "ğŸ”º "

[rlang]
symbol = "ğŸ“ "

[ruby]
symbol = "îœ¹ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[shlvl]
symbol = "â†•ï¸  "

[singularity]
symbol = ""

[swift]
symbol = "î• "

[terraform]
symbol = "ï¨ˆ "

[vagrant]
symbol = "â± "

[vcsh]
symbol = ""

[vlang]
symbol = "V "

[zig]
symbol = "â†¯ "
